# Generated by Django 4.2.11 on 2024-05-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image_filter_post_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='year_of_artwork',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
