# Generated by Django 4.2.11 on 2024-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_artist_name_post_year_of_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
